### ISSUE TITLE
 'dns': <[uint32 ]> error

### ISSUE THREAD

**Issue by TheBarzFR** [home-assistant/cli#307] opened 2021-08-02 08:48 UTC
Hello,
I got error using the following command about DNS settings:

ha network set ens18 --ipv4-nameserver=10.128.xxx.xxx
Error: Error parsing parameter 1 of type “a{sa{sv}}”: expected value:
              'dns': <[uint32 ]>,
                              ^

There a space characters on variable définition.

**Comment by kubilay902** [comment] 2021-08-06 18:52
Same here... 
![image](https://user-images.githubusercontent.com/3920736/128558418-18521f33-7889-4a46-bf5e-e91c08c77be2.png)

**Comment by ludeeus** [comment] 2021-08-10 09:35
Add quotes around the adress

**Comment by TheBarzFR** [comment] 2021-08-10 10:33
Same with double or simple quotes:
root@uxiot01:/opt/hass.io/ssl# ha network set ens18 --ipv4-nameserver='10.128.x.x'
Error: Error parsing parameter 1 of type “a{sa{sv}}”: expected value:
              'dns': <[uint32 ]>,
                              ^
root@uxiot01:/opt/hass.io/ssl# ha network set ens18 --ipv4-nameserver="10.128.x.x"
Error: Error parsing parameter 1 of type “a{sa{sv}}”: expected value:
              'dns': <[uint32 ]>,
                              ^

**Comment by ludeeus** [comment] 2021-08-10 10:38
try: `ha network update ens18 --ipv4-nameserver "10.128.x.x"`
If that does not work, what IP are you trying with? there are no reason in hiding local IP's
And paste information from system health https://www.home-assistant.io/more-info/system-health#github-issues

**Comment by TheBarzFR** [comment] 2021-08-10 12:18
I'm running under ubuntu 20. I knew is unsupported version; but ...

See attatched informations:
# ha network update ens18 --ipv4-nameserver "10.128.10.254"
Error: Error parsing parameter 1 of type “a{sa{sv}}”: expected value:
              'dns': <[uint32 ]>,

## System Health

version | core-2021.7.4
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.4.0-80-generic
arch | x86_64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.13.2
Stage | running
Available Repositories | 906
Installed Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Ubuntu 20.04.2 LTS
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.7
disk_total | 78.2 GB
disk_used | 16.3 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.8.0), ESPHome (1.20.4), SSH & Web Terminal (9.0.0), File editor (5.3.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 3
views | 4
mode | storage

</details>

**Comment by ludeeus** [comment] 2021-08-10 12:22
That's what I thought since I'm not able to reproduce on a supported system.
If anyone is able to do that, please open a new issue for it :+1: 

Closing this for now as there is no reproduction on a supported system.

**Closed by ludeeus** 2021-08-10 12:22 UTC
